version: '3.7'

services:
  zendesk-app:
    container_name: so-zen-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - case_app_node_modules:/app/node_modules
    ports:
      - 8080:8080
      - 4567:4567
    environment:
      - CHOKIDAR_USEPOLLING=true
      - RUBYOPT=-E UTF-8
    stdin_open: true
    tty: true
volumes:
  case_app_node_modules: